#!/bin/bash


if [[ "$#" -ne 1 || ! "$1" =~ ^[0-9]{4}$ ]]; then
    echo "Usage: $0 <4-digit integer>"
    exit 1
fi

input=$1

echo -n "$input" | sha256sum > hash_output.txt

echo "Hash generated and saved in hash_output.txt"

